---
- hosts: all
  tasks:
    - name: get uptime
      shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
      register: uptime

    - debug: var={{ item }}
      with_items:
        - uptime.stdout
